# Build step #1: build the React front end
FROM node:16-alpine as build-step
WORKDIR /app
ENV PATH /front-end-next/node_modules/.bin:$PATH
COPY package.json yarn.lock ./
COPY ./src ./src
COPY ./public ./public
RUN yarn install
RUN yarn build
RUN yarn export -o ../build/

# Build step #2: build an nginx container
FROM nginx:stable-alpine
COPY --from=build-step /build /usr/share/nginx/html
COPY ./nginx.default.conf /etc/nginx/conf.d/default.conf