FROM python:3.9
WORKDIR /app

COPY flask-server flask-server/
COPY uploads   uploads/
COPY output     output/

RUN ls
RUN ls -R flask-server
RUN pip install -r flask-server/requirement.txt


ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "api:app"]