FROM python:3.9
WORKDIR /app

COPY flask-server flask-server/
COPY uploads   uploads/
COPY output     output/


RUN pip install -r flask-server/requirement.txt

WORKDIR /app/flask-server

ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "server:app"]