FROM python:3.9
WORKDIR /app

COPY flask-server ./
COPY uploads   ./
COPY output     ./

RUN pip install -r ./flask-server/requirements.txt

ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "api:app"]